### ISSUE TITLE
output gcode has NAN values

### ISSUE THREAD

**Issue by elektroluki** [evnor/dragknife-repath#1] opened 2024-05-25 23:25 UTC
using the exe file in windows and converting a file, the results include NANs and many paths cannot be processed by the CNC. Input and output file and settings are attached.
Other files i have tested worked perfectly - thank your for the tool!

[output.txt](https://github.com/evnor/dragknife-repath/files/15445380/output.txt)
[input.txt](https://github.com/evnor/dragknife-repath/files/15445381/input.txt)
![dragknife-repath-settings](https://github.com/evnor/dragknife-repath/assets/76393776/e56bc8fe-9bbf-4610-aef1-b95b871bade9)

**Comment by evnor** [comment] 2024-05-27 16:51
Hello! Thank you for my first issue! Nice to see someone else use this, and I'm surprised you managed to find it. What have you been using it for?

It seems the NaN values were caused by a divide-by-zero when normalizing. However, after fixing that, the output of your test input still looks very while others seem to work fine. I don't have time to look further in the next two weeks, but I will eventually come to it.

The divide-by-zero has been fixed, but the .exe has not been updated.

**Comment by elektroluki** [comment] 2024-05-27 23:07
Thank you for the work! I was searching for an easy way to correct for the drag-knife drag. I was printing stickers which I designed in Inkscape and exported to g-code by using the gcodetools plugin. There is however no tool correction available (which I could make work) in inkscape. Your exe file did the trick for a first few projects for my kids until I ran into that issue.

Thanks again. If you find time an update of the exe file would be nice, but no hurry.

Lukas

Von: evnor ***@***.***>
Gesendet: Monday, May 27, 2024 18:52
An: evnor/dragknife-repath ***@***.***>
Cc: Mayer, Lukas W. ***@***.***>; Author ***@***.***>
Betreff: Re: [evnor/dragknife-repath] output gcode has NAN values (Issue #1)


Hello! Thank you for my first issue! Nice to see someone else use this, and I'm surprised you managed to find it. What have you been using it for?

It seems the NaN values were caused by a divide-by-zero when normalizing. However, after fixing that, the output of your test input still looks very while others seem to work fine. I don't have time to look further in the next two weeks, but I will eventually come to it.

The divide-by-zero has been fixed, but the .exe has not been updated.

**Comment by evnor** [comment] 2024-06-08 14:53
This should be fixed by [23e5aca](https://github.com/evnor/dragknife-repath/commit/23e5acaaaabaa4105e4278832294c83bf7151cf6), [43dfc46](https://github.com/evnor/dragknife-repath/commit/43dfc4684bb112fcc8e2936365406c95949e1358), and [44aed81](https://github.com/evnor/dragknife-repath/commit/44aed81c5b2323aca6c52d7f8a824c4fa274adc9). The main problem was that the penetration is perfectly vertical, so the program did not know in which direction to offset the knife. Also, the GCode parsing library outputs some commands twice: once without arguments and once with arguments. We now detect the former and discard the command. The .exe has been updated. Hope this works!

**Closed as completed by evnor** 2024-06-08 14:53 UTC
